version: '2'
services:
    treemarks-app:
        image: treemarks
        external_links:
            - treemarks-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/treemarks
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    treemarks-postgresql:
        extends:
            file: postgresql.yml
            service: treemarks-postgresql
